### PR TITLE
Working ingress

### LINKED ISSUE #85: K8s install should configure an ingress
Currently there is no Ingress for the k8s install but the TAS install configures `gateway-demo.yourdomain.com` as a route.

Later in the [instructions](https://github.com/spring-cloud-services-samples/animal-rescue#gateway-and-animal-rescue-application-features), it uses the URL of `gateway-demo.yourdomain.com`.

Creating an ingress for the k8s install will allow that instruction to work on both K8s and TAS.

### PR DESCRIPTION
**Pull request by mikegehard**
This will allow people to use the same instructions
as is used in the TAS install and not need the tunnel.

[Fixes #85]

### CODE REVIEW

**Review by csterwa — CHANGES_REQUESTED** [review]
Is there documentation on how to set DOMAIN in your environment via terminal? Windows?

**Comment by mikegehard** [comment]
Wasn't planning on having them set and env var but in instead have them change the file directly as outlined.

Maybe change the "placeholder" so there isn't confusion?

**Comment by mikegehard** [comment]
@csterwa any thoughts on this? I'd like to get it merged in maybe with a change to the placeholder?

**Comment by csterwa** [comment]
I would rather set the env var instead of changing file.

**Comment by mikegehard** [comment]
Unfortunately it isn't that easy to interpolate env vars into k8s manifests. 

In the same file, we hardcode a bogus URL for the server for OpenAPI docs and assume that the user will change that to match.

**Comment by csterwa** [comment]
Then editing directly is best for now. I want to discuss options on how to make this better. I think implementing our own K8s Gateway would be best to resolve this but that is longer term goal.

**Review by csterwa — APPROVED** [review]

**Pull request merged**
